#!/bin/bash

echo "installing: realpath autoconf automake build-essential checkinstall git libtool pkg-config texi2html python curl wget graphicsmagick"

apt-get install -y \
  realpath \
  autoconf \
  automake \
  build-essential \
  checkinstall \
  git \
  libtool \
  pkg-config \
  texi2html \
  python \
  curl \
  wget \
  graphicsmagick \
  sendmail > /dev/null 2>&1

echo "installation completed"